<a href="https://colab.research.google.com/github/sefakurtipek/pytorchTutorials/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
print(torch.__version__)
# Create random tensor
rand_tensor = torch.rand(size=(7,7))
rand_tensor

2.1.0+cu121


tensor([[0.9652, 0.4563, 0.9559, 0.7367, 0.5033, 0.5079, 0.2078],
        [0.8974, 0.0251, 0.4401, 0.3505, 0.6741, 0.9640, 0.5443],
        [0.6007, 0.6610, 0.4796, 0.8186, 0.5026, 0.4628, 0.4079],
        [0.7481, 0.7726, 0.6184, 0.8055, 0.8774, 0.5814, 0.7529],
        [0.3684, 0.2968, 0.9864, 0.4851, 0.9287, 0.1876, 0.4234],
        [0.7825, 0.9441, 0.8726, 0.4620, 0.0033, 0.5670, 0.4126],
        [0.5985, 0.0653, 0.8865, 0.1555, 0.3114, 0.7564, 0.0464]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
matrix_1 = torch.rand(size=(1,7))
matrix_2 = torch.rand(size=(1,7))
# Perform matrix multiplication
matrix_mul = matrix_1 * matrix_2.T
matrix_mul

tensor([[0.1052, 0.0791, 0.1837, 0.1047, 0.2035, 0.2231, 0.0574],
        [0.0593, 0.0446, 0.1035, 0.0590, 0.1146, 0.1257, 0.0323],
        [0.0978, 0.0735, 0.1706, 0.0972, 0.1890, 0.2072, 0.0533],
        [0.0316, 0.0237, 0.0551, 0.0314, 0.0610, 0.0669, 0.0172],
        [0.1681, 0.1264, 0.2934, 0.1672, 0.3251, 0.3564, 0.0917],
        [0.1754, 0.1319, 0.3062, 0.1745, 0.3392, 0.3719, 0.0957],
        [0.0405, 0.0304, 0.0707, 0.0403, 0.0783, 0.0858, 0.0221]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
import random
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)
# Create two random tensors
random_tensor_1 = torch.rand(3,4)
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_2 = torch.rand(3,4)
# Matrix multiply tensors
random_tensor_mul_2 = torch.matmul(random_tensor_1.T, random_tensor_2)
random_tensor_mul_2

tensor([[0.5484, 0.8643, 0.3535, 0.5241],
        [0.8643, 1.3920, 0.5993, 0.9239],
        [0.3535, 0.5993, 0.3697, 0.5912],
        [0.5241, 0.9239, 0.5912, 0.9824]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
RANDOM_SEED_CUDA = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED_CUDA)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(seed=RANDOM_SEED_CUDA)
# Check for access to GPU
if torch.cuda.is_available():
    print("CUDA is available. GPU Info:")
    print(torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("CUDA is not available.")
# Create two random tensors on GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

# Print device and the tensors
print(f"Device: {device}\n({tensor_A},\n {tensor_B})")

CUDA is available. GPU Info:
Tesla T4
Device: cuda
(tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
matmul_operation = torch.matmul(tensor_A, tensor_B.T)
matmul_operation, matmul_operation.size()

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = torch.max(matmul_operation)
# Find min
min_value = torch.min(matmul_operation)
print(f"(Max value: {max_value},\n Min value:{min_value})")

(Max value: 0.7667766809463501,
 Min value:0.27863210439682007)


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
arg_max_matmul_operation = matmul_operation.argmax()
# Find arg min
arg_min_matmul_operation = matmul_operation.argmin()
print(f"(maximum index value of the output of matmul_operation: {arg_max_matmul_operation},\n minimum index value of the output of matmul_operation:{arg_min_matmul_operation})")

(maximum index value of the output of matmul_operation: 1,
 minimum index value of the output of matmul_operation:0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)

# Create random tensor
rand_tensor_last = torch.rand(size=(1,1,1,10))
print(rand_tensor_last, rand_tensor_last.size())
# Remove single dimensions
only_last = torch.squeeze(rand_tensor_last)

# Print out tensors and their shapes
print(only_last, only_last.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
